/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.galguladornasterydach;

/**
 *
 * @author soroczynskijan i odrobinaadrian też
 */
public class galguladorNaSterydach extends javax.swing.JFrame {

    /**
     * Creates new form galguladorNaSterydach
     */
    public galguladorNaSterydach() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsaoekran = new javax.swing.JLabel();
        jsaosinus = new javax.swing.JButton();
        jsaotangens = new javax.swing.JButton();
        jsaoznakrownosci = new javax.swing.JButton();
        jsaocotangens = new javax.swing.JButton();
        jsaoodpowiedz = new javax.swing.JButton();
        jsaocosinus = new javax.swing.JButton();
        jsaoplus = new javax.swing.JButton();
        jsaodelete = new javax.swing.JButton();
        jsaomnozenie = new javax.swing.JButton();
        jsaorazydziesiec = new javax.swing.JButton();
        jsaodominuspierwszej = new javax.swing.JButton();
        jsaopi = new javax.swing.JButton();
        jsaominus = new javax.swing.JButton();
        jsaopierwiastek = new javax.swing.JButton();
        jsaonawiasy = new javax.swing.JButton();
        jsaosilnia = new javax.swing.JButton();
        jsaodotrzeciej = new javax.swing.JButton();
        jsaododrugiej = new javax.swing.JButton();
        jsaodziel = new javax.swing.JButton();
        jsaoprocenty = new javax.swing.JButton();
        jsaoliczbunki = new javax.swing.JTextField();
        jsaoliczbenki = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("kalkulator (od siedmiu boleści)");

        jsaoekran.setToolTipText("wyrocznia mówi");

        jsaosinus.setText("sin");
        jsaosinus.setToolTipText("kont");
        jsaosinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaosinusActionPerformed(evt);
            }
        });

        jsaotangens.setText("tg");
        jsaotangens.setToolTipText("kult");
        jsaotangens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaotangensActionPerformed(evt);
            }
        });

        jsaoznakrownosci.setText("=");
        jsaoznakrownosci.setToolTipText("dobrze trafiłeś");
        jsaoznakrownosci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaoznakrownosciActionPerformed(evt);
            }
        });

        jsaocotangens.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jsaocotangens.setText("ctg");
        jsaocotangens.setToolTipText("kazik");
        jsaocotangens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaocotangensActionPerformed(evt);
            }
        });

        jsaoodpowiedz.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jsaoodpowiedz.setText("Ans");
        jsaoodpowiedz.setToolTipText("->");
        jsaoodpowiedz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaoodpowiedzActionPerformed(evt);
            }
        });

        jsaocosinus.setText("cos");
        jsaocosinus.setToolTipText("kont");
        jsaocosinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaocosinusActionPerformed(evt);
            }
        });

        jsaoplus.setText("+");
        jsaoplus.setToolTipText("dodaje");
        jsaoplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaoplusActionPerformed(evt);
            }
        });

        jsaodelete.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jsaodelete.setText("DEL");
        jsaodelete.setToolTipText("inspiro");
        jsaodelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaodeleteActionPerformed(evt);
            }
        });

        jsaomnozenie.setText("*");
        jsaomnozenie.setToolTipText("lulajże jezuniu");
        jsaomnozenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaomnozenieActionPerformed(evt);
            }
        });

        jsaorazydziesiec.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jsaorazydziesiec.setText("x10");
        jsaorazydziesiec.setToolTipText("WINCYJ");
        jsaorazydziesiec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaorazydziesiecActionPerformed(evt);
            }
        });

        jsaodominuspierwszej.setText("x-¹");
        jsaodominuspierwszej.setToolTipText("przez 0");
        jsaodominuspierwszej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaodominuspierwszejActionPerformed(evt);
            }
        });

        jsaopi.setText("π");
        jsaopi.setToolTipText("nie lubię głagolicy");
        jsaopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaopiActionPerformed(evt);
            }
        });

        jsaominus.setText("-");
        jsaominus.setToolTipText("odejmuje");
        jsaominus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaominusActionPerformed(evt);
            }
        });

        jsaopierwiastek.setText("√");
        jsaopierwiastek.setToolTipText("oskar pierwiastek");
        jsaopierwiastek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaopierwiastekActionPerformed(evt);
            }
        });

        jsaonawiasy.setText("()");
        jsaonawiasy.setToolTipText(":-)");
        jsaonawiasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaonawiasyActionPerformed(evt);
            }
        });

        jsaosilnia.setText("!");
        jsaosilnia.setToolTipText("SILNIA!!!!");
        jsaosilnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaosilniaActionPerformed(evt);
            }
        });

        jsaodotrzeciej.setText("x³");
        jsaodotrzeciej.setToolTipText("cube");
        jsaodotrzeciej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaodotrzeciejActionPerformed(evt);
            }
        });

        jsaododrugiej.setText("x²");
        jsaododrugiej.setToolTipText("square");
        jsaododrugiej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaododrugiejActionPerformed(evt);
            }
        });

        jsaodziel.setText("/");
        jsaodziel.setToolTipText("przez 0");
        jsaodziel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaodzielActionPerformed(evt);
            }
        });

        jsaoprocenty.setText("%");
        jsaoprocenty.setToolTipText("dobre wiśniowe");
        jsaoprocenty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaoprocentyActionPerformed(evt);
            }
        });

        jsaoliczbunki.setText("0");
        jsaoliczbunki.setToolTipText("tu się pierwszą liczbę daje");
        jsaoliczbunki.setMinimumSize(new java.awt.Dimension(70, 30));
        jsaoliczbunki.setPreferredSize(new java.awt.Dimension(70, 30));

        jsaoliczbenki.setText("0");
        jsaoliczbenki.setToolTipText("tu się drugą liczbę daje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jsaodelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsaosinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsaonawiasy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jsaocosinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jsaotangens, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jsaopierwiastek, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jsaododrugiej, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jsaopi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jsaodominuspierwszej, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jsaocotangens, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jsaoodpowiedz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jsaorazydziesiec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(jsaoplus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jsaosilnia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jsaodotrzeciej, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jsaomnozenie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsaoliczbenki, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jsaoliczbunki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jsaominus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jsaodziel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jsaoprocenty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jsaoznakrownosci, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jsaoekran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jsaoekran)
                .addGap(18, 18, 18)
                .addComponent(jsaoliczbunki, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jsaoliczbenki, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsaoprocenty)
                    .addComponent(jsaosilnia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsaodziel)
                    .addComponent(jsaomnozenie)
                    .addComponent(jsaodotrzeciej)
                    .addComponent(jsaododrugiej)
                    .addComponent(jsaopierwiastek)
                    .addComponent(jsaonawiasy))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsaominus)
                    .addComponent(jsaoplus)
                    .addComponent(jsaorazydziesiec)
                    .addComponent(jsaodominuspierwszej)
                    .addComponent(jsaopi)
                    .addComponent(jsaodelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsaoznakrownosci)
                    .addComponent(jsaoodpowiedz)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jsaocotangens)
                        .addComponent(jsaotangens)
                        .addComponent(jsaocosinus)
                        .addComponent(jsaosinus)))
                .addGap(79, 79, 79))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jsaoodpowiedzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaoodpowiedzActionPerformed
        /** 
         * przypomina
         */
        jsaoekran.setText("= jest tuż obok, jakby coś.");
    }//GEN-LAST:event_jsaoodpowiedzActionPerformed

    private void jsaoznakrownosciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaoznakrownosciActionPerformed
        /**
         * wyświetla
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        jsaoekran.setText(liczba1 + "" + liczba2);
    }//GEN-LAST:event_jsaoznakrownosciActionPerformed

    private void jsaoplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaoplusActionPerformed
        /**
         * dodaje i wyświetla
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double dodawanie = liczba1 + liczba2;
        jsaoekran.setText("" + dodawanie);
    }//GEN-LAST:event_jsaoplusActionPerformed

    private void jsaominusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaominusActionPerformed
        /**
         * odejmuje i wyświetla
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double odejmowanie = liczba1 - liczba2;
        jsaoekran.setText("" + odejmowanie);
    }//GEN-LAST:event_jsaominusActionPerformed

    private void jsaomnozenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaomnozenieActionPerformed
        /**
         * mnoży i wyświetla
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double mnozenie = liczba1 * liczba2;
        jsaoekran.setText("" + mnozenie);
    }//GEN-LAST:event_jsaomnozenieActionPerformed

    private void jsaodzielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaodzielActionPerformed
        /**
         * dzieli i wyświetla
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double dzielenie = liczba1 / liczba2;
        if (liczba2==0){
            jsaoekran.setText("Człowieku, co ty robisz? Opamiętaj się!");
        }
        else{
        jsaoekran.setText("" + dzielenie);
        }
    }//GEN-LAST:event_jsaodzielActionPerformed

    private void jsaododrugiejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaododrugiejActionPerformed
        /**
         * potęguje i wyświetla
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double potega1 = liczba1 * liczba1;
        double potega2 = liczba2 * liczba2;
        jsaoekran.setText("" + potega1 + ", " + potega2);
    }//GEN-LAST:event_jsaododrugiejActionPerformed

    private void jsaodotrzeciejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaodotrzeciejActionPerformed
        /**
         * potęguje, jeszcze raz potęguje, a potem wyświetla
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double wiekszapotega1 = liczba1*liczba1*liczba1;
        double wiekszapotega2 = liczba2*liczba2*liczba2;
        jsaoekran.setText(""+wiekszapotega1+", "+wiekszapotega2);
    }//GEN-LAST:event_jsaodotrzeciejActionPerformed

    private void jsaodominuspierwszejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaodominuspierwszejActionPerformed
        /**
         * odwraca i wyświetla
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double dominuspierwszej = 1/liczba1;
        double dominusdrugiej = 1/liczba2;
        jsaoekran.setText(""+dominuspierwszej+", "+dominusdrugiej);
    }//GEN-LAST:event_jsaodominuspierwszejActionPerformed

    private void jsaorazydziesiecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaorazydziesiecActionPerformed
        /**
         * mnoży przez dziesięć i wyświetla
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double razydziesiec = 10*liczba1;
        double razyjedenascie = 10*liczba2;
        jsaoekran.setText(""+razydziesiec+", "+razyjedenascie);
    }//GEN-LAST:event_jsaorazydziesiecActionPerformed

    private void jsaoprocentyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaoprocentyActionPerformed
        /**
         * dzieli przez sto i wyświetla
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double pierwszeprocenty = liczba1/100;
        /** i teraz z górki
         */
        double drugieprocenty = liczba2/100;
        jsaoekran.setText(""+pierwszeprocenty+", "+drugieprocenty);
    }//GEN-LAST:event_jsaoprocentyActionPerformed

    private void jsaocotangensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaocotangensActionPerformed
        /**
         * wyświetla cotangens
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        /** Chodził tyle lat, aż wpadł w niski ton
         * Początek zeznania w sprawie, którą znam
         * Niewiele się zmieniło w otoczeniu starym
         * Tyram 27 lat pod tym zegarem
         * Wysoki Sądzie! Ja z narkotykami
         * Miałem tyle wspólnego, co z Mercedesami;
         * Czyli nic, i nigdy nie uwierzę
         * Aby moje dziecko miało cokolwiek z tym bliżej
         * Od niedawna chodził ubrany lepiej
         * Niż jego rówieśnicy ze szkoły średniej
         * Ale ja go nie pytałem, ja czasu nie miałem
         * By dać żreć im wszystkim na dwie zmiany tyrałem
         * Jego brat jest we wojsku, jak Pan Bóg przykazał
         * Siostra starsza ma męża na medal
         * Siostra młodsza w tym roku kończy podstawówkę
         * Nie wierzę, że sprzedaje narkotyki uczniom!
         * 
         * To dobry chłopak był i mało pił
         * To dobry chłopak był i mało pił
         * To dobry chłopak był i mało pił
         * To dobry chłopak był i mało pił
         * 
         * Working hard for the Hardzone now...
         */
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double tangens1 = (1/Math.tan(liczba1));
        double tangens2 = (1/Math.tan(liczba2));
        jsaoekran.setText(""+tangens1+", "+tangens2); 
    }//GEN-LAST:event_jsaocotangensActionPerformed

    private void jsaopierwiastekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaopierwiastekActionPerformed
        /**
         * pierwiastkuje i wyświetla
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double pierwiastek1 = (double) Math.sqrt(liczba1);
        double pierwiastek2 = (double) Math.sqrt(liczba1);
        jsaoekran.setText(""+pierwiastek1+", "+pierwiastek2);
    }//GEN-LAST:event_jsaopierwiastekActionPerformed

    private void jsaonawiasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaonawiasyActionPerformed
        /**
         * podaje nawiasy do stołu
         */
        jsaoekran.setText("Proszę, częstuj się: (((((((())))))))");
    }//GEN-LAST:event_jsaonawiasyActionPerformed

    private void jsaodeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaodeleteActionPerformed
        /**
         * usuwa tekst
         */
        jsaoekran.setText("");
    }//GEN-LAST:event_jsaodeleteActionPerformed

    private void jsaopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaopiActionPerformed
       /**
        * wyświetla pi
        */
        float pi = (float) Math.PI;
       jsaoekran.setText(""+pi);
    }//GEN-LAST:event_jsaopiActionPerformed

    private void jsaosilniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaosilniaActionPerformed
        /**
         * próbuje wyświetlić silnię
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        for (double i=liczba1; i>3;i--){
            liczba1*=i;
        }
        for (double j=liczba2; j>3; j--){
            liczba2*=j;
        }
        jsaoekran.setText(""+liczba1+", "+liczba2);
    }//GEN-LAST:event_jsaosilniaActionPerformed

    private void jsaosinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaosinusActionPerformed
        /**
         * wyświetla sinus
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double sinus1 = Math.sin(liczba1);
        double sinus2 = Math.sin(liczba2);
        jsaoekran.setText(""+sinus1+", "+sinus2);
    }//GEN-LAST:event_jsaosinusActionPerformed

    private void jsaocosinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaocosinusActionPerformed
        /**
         * wyświetla cosinus
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double cosinus1 = Math.cos(liczba1);
        double cosinus2 = Math.cos(liczba2);
        jsaoekran.setText(""+cosinus1+", "+cosinus2);
    }//GEN-LAST:event_jsaocosinusActionPerformed

    private void jsaotangensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaotangensActionPerformed
        /**
         * wyświetla tangens
         */
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        /**
         * Zabiłem ministra finansów
        Gdy do mnie w nocy włamał się
        Chciał wynieść z domu moje rzeczy
        Przecież dla niego skończyło się źle
        * 
        Zabiłem ministra finansów
        W samoobronie strzały te
        Czy teraz mnie aresztujecie?
        Przecież broniłem tylko się
        * 
        Strzelałem wiele nie myślałem
        Tak się w napięciu reaguje
        Nie myślałem, spanikowałem
        Ale niewinny się czuje
        * 
        Gdy to się stało, ciągle mi było za mało
        Gdy to się stało, ciągle mi było za mało
        Gdy to się stało, ciągle mi było za mało
        Gdy to się stało
        Gdy to się stało
        * 
        Zabiłem ministra finansów
        Gdy do mnie w nocy włamał się
        Chciał ukraść moje własne rzeczy
        Teraz zabity leży gdzieś
        * 
        Gdy to się stało, ciągle mi było za mało
        Gdy to się stało, ciągle mi było za mało
        Gdy to się stało, ciągle mi było za mało
        Gdy to się stało
        Gdy to się stało.
         */
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double tangens1 = Math.tan(liczba1);
        double tangens2 = Math.tan(liczba2);
        jsaoekran.setText(""+tangens1+", "+tangens2);
    }//GEN-LAST:event_jsaotangensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (doubleroduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(galguladorNaSterydach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(galguladorNaSterydach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(galguladorNaSterydach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(galguladorNaSterydach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new galguladorNaSterydach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jsaocosinus;
    private javax.swing.JButton jsaocotangens;
    private javax.swing.JButton jsaodelete;
    private javax.swing.JButton jsaododrugiej;
    private javax.swing.JButton jsaodominuspierwszej;
    private javax.swing.JButton jsaodotrzeciej;
    private javax.swing.JButton jsaodziel;
    private javax.swing.JLabel jsaoekran;
    private javax.swing.JTextField jsaoliczbenki;
    private javax.swing.JTextField jsaoliczbunki;
    private javax.swing.JButton jsaominus;
    private javax.swing.JButton jsaomnozenie;
    private javax.swing.JButton jsaonawiasy;
    private javax.swing.JButton jsaoodpowiedz;
    private javax.swing.JButton jsaopi;
    private javax.swing.JButton jsaopierwiastek;
    private javax.swing.JButton jsaoplus;
    private javax.swing.JButton jsaoprocenty;
    private javax.swing.JButton jsaorazydziesiec;
    private javax.swing.JButton jsaosilnia;
    private javax.swing.JButton jsaosinus;
    private javax.swing.JButton jsaotangens;
    private javax.swing.JButton jsaoznakrownosci;
    // End of variables declaration//GEN-END:variables
}
