/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.galguladornasterydach;

/**
 *
 * @author soroczynskijan
 */
public class galguladorNaSterydach extends javax.swing.JFrame {

    /**
     * Creates new form galguladorNaSterydach
     */
    public galguladorNaSterydach() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsaoekran = new javax.swing.JLabel();
        jsaosinus = new javax.swing.JButton();
        jsaotangens = new javax.swing.JButton();
        jsaoznakrownosci = new javax.swing.JButton();
        jsaocotangens = new javax.swing.JButton();
        jsaoodpowiedz = new javax.swing.JButton();
        jsaocosinus = new javax.swing.JButton();
        jsaoplus = new javax.swing.JButton();
        jsaodelete = new javax.swing.JButton();
        jsaomnozenie = new javax.swing.JButton();
        jsaorazydziesiec = new javax.swing.JButton();
        jsaodominuspierwszej = new javax.swing.JButton();
        jsaopi = new javax.swing.JButton();
        jsaominus = new javax.swing.JButton();
        jsaopierwiastek = new javax.swing.JButton();
        jsaonawiasy = new javax.swing.JButton();
        jsaosilnia = new javax.swing.JButton();
        jsaodotrzeciej = new javax.swing.JButton();
        jsaododrugiej = new javax.swing.JButton();
        jsaodziel = new javax.swing.JButton();
        jsaoprocenty = new javax.swing.JButton();
        jsaoliczbunki = new javax.swing.JTextField();
        jsaoliczbenki = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jsaoekran.setToolTipText("");

        jsaosinus.setText("sin");
        jsaosinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaosinusActionPerformed(evt);
            }
        });

        jsaotangens.setText("tg");
        jsaotangens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaotangensActionPerformed(evt);
            }
        });

        jsaoznakrownosci.setText("=");
        jsaoznakrownosci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaoznakrownosciActionPerformed(evt);
            }
        });

        jsaocotangens.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jsaocotangens.setText("ctg");
        jsaocotangens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaocotangensActionPerformed(evt);
            }
        });

        jsaoodpowiedz.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jsaoodpowiedz.setText("Ans");
        jsaoodpowiedz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaoodpowiedzActionPerformed(evt);
            }
        });

        jsaocosinus.setText("cos");
        jsaocosinus.setToolTipText("");
        jsaocosinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaocosinusActionPerformed(evt);
            }
        });

        jsaoplus.setText("+");
        jsaoplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaoplusActionPerformed(evt);
            }
        });

        jsaodelete.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jsaodelete.setText("DEL");
        jsaodelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaodeleteActionPerformed(evt);
            }
        });

        jsaomnozenie.setText("*");
        jsaomnozenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaomnozenieActionPerformed(evt);
            }
        });

        jsaorazydziesiec.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jsaorazydziesiec.setText("x10");
        jsaorazydziesiec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaorazydziesiecActionPerformed(evt);
            }
        });

        jsaodominuspierwszej.setText("x-¹");
        jsaodominuspierwszej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaodominuspierwszejActionPerformed(evt);
            }
        });

        jsaopi.setText("π");
        jsaopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaopiActionPerformed(evt);
            }
        });

        jsaominus.setText("-");
        jsaominus.setToolTipText("");
        jsaominus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaominusActionPerformed(evt);
            }
        });

        jsaopierwiastek.setText("√");
        jsaopierwiastek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaopierwiastekActionPerformed(evt);
            }
        });

        jsaonawiasy.setText("()");
        jsaonawiasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaonawiasyActionPerformed(evt);
            }
        });

        jsaosilnia.setText("!");
        jsaosilnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaosilniaActionPerformed(evt);
            }
        });

        jsaodotrzeciej.setText("x³");
        jsaodotrzeciej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaodotrzeciejActionPerformed(evt);
            }
        });

        jsaododrugiej.setText("x²");
        jsaododrugiej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaododrugiejActionPerformed(evt);
            }
        });

        jsaodziel.setText("/");
        jsaodziel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaodzielActionPerformed(evt);
            }
        });

        jsaoprocenty.setText("%");
        jsaoprocenty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaoprocentyActionPerformed(evt);
            }
        });

        jsaoliczbunki.setText("0");
        jsaoliczbunki.setMinimumSize(new java.awt.Dimension(70, 30));
        jsaoliczbunki.setPreferredSize(new java.awt.Dimension(70, 30));

        jsaoliczbenki.setText("0");
        jsaoliczbenki.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jsaodelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsaosinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsaonawiasy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jsaocosinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jsaotangens, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jsaopierwiastek, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jsaododrugiej, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jsaopi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jsaodominuspierwszej, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jsaocotangens, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jsaoodpowiedz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jsaorazydziesiec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(jsaoplus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jsaosilnia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jsaodotrzeciej, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jsaomnozenie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsaoliczbenki, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jsaoliczbunki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jsaominus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jsaodziel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jsaoprocenty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jsaoznakrownosci, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jsaoekran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jsaoekran)
                .addGap(18, 18, 18)
                .addComponent(jsaoliczbunki, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jsaoliczbenki, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsaoprocenty)
                    .addComponent(jsaosilnia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsaodziel)
                    .addComponent(jsaomnozenie)
                    .addComponent(jsaodotrzeciej)
                    .addComponent(jsaododrugiej)
                    .addComponent(jsaopierwiastek)
                    .addComponent(jsaonawiasy))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsaominus)
                    .addComponent(jsaoplus)
                    .addComponent(jsaorazydziesiec)
                    .addComponent(jsaodominuspierwszej)
                    .addComponent(jsaopi)
                    .addComponent(jsaodelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsaoznakrownosci)
                    .addComponent(jsaoodpowiedz)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jsaocotangens)
                        .addComponent(jsaotangens)
                        .addComponent(jsaocosinus)
                        .addComponent(jsaosinus)))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsaoodpowiedzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaoodpowiedzActionPerformed
        jsaoekran.setText("= jest tuż obok, jakby coś.");
    }//GEN-LAST:event_jsaoodpowiedzActionPerformed

    private void jsaoznakrownosciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaoznakrownosciActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        int liczba1 = Integer.parseInt(liczbunki);
        int liczba2 = Integer.parseInt(liczbenki);
        jsaoekran.setText(liczba1 + "" + liczba2);
    }//GEN-LAST:event_jsaoznakrownosciActionPerformed

    private void jsaoplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaoplusActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        int liczba1 = Integer.parseInt(liczbunki);
        int liczba2 = Integer.parseInt(liczbenki);
        int dodawanie = liczba1 + liczba2;
        jsaoekran.setText("" + dodawanie);
    }//GEN-LAST:event_jsaoplusActionPerformed

    private void jsaominusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaominusActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        int liczba1 = Integer.parseInt(liczbunki);
        int liczba2 = Integer.parseInt(liczbenki);
        int odejmowanie = liczba1 - liczba2;
        jsaoekran.setText("" + odejmowanie);
    }//GEN-LAST:event_jsaominusActionPerformed

    private void jsaomnozenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaomnozenieActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        int liczba1 = Integer.parseInt(liczbunki);
        int liczba2 = Integer.parseInt(liczbenki);
        int mnozenie = liczba1 * liczba2;
        jsaoekran.setText("" + mnozenie);
    }//GEN-LAST:event_jsaomnozenieActionPerformed

    private void jsaodzielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaodzielActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        int liczba1 = Integer.parseInt(liczbunki);
        int liczba2 = Integer.parseInt(liczbenki);
        int dzielenie = liczba1 / liczba2;
        jsaoekran.setText("" + dzielenie);
    }//GEN-LAST:event_jsaodzielActionPerformed

    private void jsaododrugiejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaododrugiejActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        int liczba1 = Integer.parseInt(liczbunki);
        int liczba2 = Integer.parseInt(liczbenki);
        int potega1 = liczba1 * liczba1;
        int potega2 = liczba2 * liczba2;
        jsaoekran.setText("" + potega1 + ", " + potega2);
    }//GEN-LAST:event_jsaododrugiejActionPerformed

    private void jsaodotrzeciejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaodotrzeciejActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        int liczba1 = Integer.parseInt(liczbunki);
        int liczba2 = Integer.parseInt(liczbenki);
        int wiekszapotega1 = liczba1*liczba1*liczba1;
        int wiekszapotega2 = liczba2*liczba2*liczba2;
        jsaoekran.setText(""+wiekszapotega1+", "+wiekszapotega2);
    }//GEN-LAST:event_jsaodotrzeciejActionPerformed

    private void jsaodominuspierwszejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaodominuspierwszejActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double dominuspierwszej = 1/liczba1;
        double dominusdrugiej = 1/liczba2;
        jsaoekran.setText(""+dominuspierwszej+", "+dominusdrugiej);
    }//GEN-LAST:event_jsaodominuspierwszejActionPerformed

    private void jsaorazydziesiecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaorazydziesiecActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        int liczba1 = Integer.parseInt(liczbunki);
        int liczba2 = Integer.parseInt(liczbenki);
        int razydziesiec = 10*liczba1;
        int razyjedenascie = 10*liczba2;
        jsaoekran.setText(""+razydziesiec+", "+razyjedenascie);
    }//GEN-LAST:event_jsaorazydziesiecActionPerformed

    private void jsaoprocentyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaoprocentyActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double pierwszeprocenty = liczba1/100;
        /** i teraz z górki
         */
        double drugieprocenty = liczba2/100;
        jsaoekran.setText(""+pierwszeprocenty+", "+drugieprocenty);
    }//GEN-LAST:event_jsaoprocentyActionPerformed

    private void jsaocotangensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaocotangensActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        /** Chodził tyle lat, aż wpadł w niski ton
         * Początek zeznania w sprawie, którą znam
         * Niewiele się zmieniło w otoczeniu starym
         * Tyram 27 lat pod tym zegarem
         * Wysoki Sądzie! Ja z narkotykami
         * Miałem tyle wspólnego, co z Mercedesami;
         * Czyli nic, i nigdy nie uwierzę
         * Aby moje dziecko miało cokolwiek z tym bliżej
         * Od niedawna chodził ubrany lepiej
         * Niż jego rówieśnicy ze szkoły średniej
         * Ale ja go nie pytałem, ja czasu nie miałem
         * By dać żreć im wszystkim na dwie zmiany tyrałem
         * Jego brat jest we wojsku, jak Pan Bóg przykazał
         * Siostra starsza ma męża na medal
         * Siostra młodsza w tym roku kończy podstawówkę
         * Nie wierzę, że sprzedaje narkotyki uczniom!
         * 
         * To dobry chłopak był i mało pił
         * To dobry chłopak był i mało pił
         * To dobry chłopak był i mało pił
         * To dobry chłopak był i mało pił
         * 
         * Working hard for the Hardzone now...
         */
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double tangens1 = (1/Math.tan(liczba1));
        double tangens2 = (1/Math.tan(liczba1));
        jsaoekran.setText(""+tangens1+", "+tangens2); 
    }//GEN-LAST:event_jsaocotangensActionPerformed

    private void jsaopierwiastekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaopierwiastekActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        int liczba1 = Integer.parseInt(liczbunki);
        int liczba2 = Integer.parseInt(liczbenki);
        int pierwiastek1 = (int) Math.sqrt(liczba1);
        int pierwiastek2 = (int) Math.sqrt(liczba1);
        jsaoekran.setText(""+pierwiastek1+", "+pierwiastek2);
    }//GEN-LAST:event_jsaopierwiastekActionPerformed

    private void jsaonawiasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaonawiasyActionPerformed
        jsaoekran.setText("Proszę, częstuj się: (((((((())))))))");
    }//GEN-LAST:event_jsaonawiasyActionPerformed

    private void jsaodeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaodeleteActionPerformed
        jsaoekran.setText("");
    }//GEN-LAST:event_jsaodeleteActionPerformed

    private void jsaopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaopiActionPerformed
        jsaoekran.setText("3.1415926535 8979323846 2643383279 5028841971 6939937510\n" +
"  5820974944 5923078164 0628620899 8628034825 3421170679\n" +
"  8214808651 3282306647 0938446095 5058223172 5359408128\n" +
"  4811174502 8410270193 8521105559 6446229489 5493038196\n" +
"  4428810975 6659334461 2847564823 3786783165 2712019091\n" +
"  4564856692 3460348610 4543266482 1339360726 0249141273\n" +
"  7245870066 0631558817 4881520920 9628292540 9171536436\n" +
"  7892590360 0113305305 4882046652 1384146951 9415116094\n" +
"  3305727036 5759591953 0921861173 8193261179 3105118548\n" +
"  0744623799 6274956735 1885752724 8912279381 8301194912");
    }//GEN-LAST:event_jsaopiActionPerformed

    private void jsaosilniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaosilniaActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        int liczba1 = Integer.parseInt(liczbunki);
        int liczba2 = Integer.parseInt(liczbenki);
        for (int i=liczba1; i>=0; i--){
            liczba1=liczba1*(liczba1-1);
        }
        for (int j=liczba2; j>=0; j--){
            liczba2=liczba2*(liczba2-1);
        }
        jsaoekran.setText(""+liczba1+", "+liczba2);
    }//GEN-LAST:event_jsaosilniaActionPerformed

    private void jsaosinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaosinusActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double sinus1 = Math.sin(liczba1);
        double sinus2 = Math.sin(liczba1);
        jsaoekran.setText(""+sinus1+", "+sinus2);
    }//GEN-LAST:event_jsaosinusActionPerformed

    private void jsaocosinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaocosinusActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double cosinus1 = Math.cos(liczba1);
        double cosinus2 = Math.cos(liczba1);
        jsaoekran.setText(""+cosinus1+", "+cosinus2);
    }//GEN-LAST:event_jsaocosinusActionPerformed

    private void jsaotangensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaotangensActionPerformed
        String liczbunki = jsaoliczbunki.getText();
        String liczbenki = jsaoliczbenki.getText();
        double liczba1 = Double.parseDouble(liczbunki);
        double liczba2 = Double.parseDouble(liczbenki);
        double tangens1 = Math.tan(liczba1);
        double tangens2 = Math.tan(liczba1);
        jsaoekran.setText(""+tangens1+", "+tangens2);
    }//GEN-LAST:event_jsaotangensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(galguladorNaSterydach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(galguladorNaSterydach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(galguladorNaSterydach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(galguladorNaSterydach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new galguladorNaSterydach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jsaocosinus;
    private javax.swing.JButton jsaocotangens;
    private javax.swing.JButton jsaodelete;
    private javax.swing.JButton jsaododrugiej;
    private javax.swing.JButton jsaodominuspierwszej;
    private javax.swing.JButton jsaodotrzeciej;
    private javax.swing.JButton jsaodziel;
    private javax.swing.JLabel jsaoekran;
    private javax.swing.JTextField jsaoliczbenki;
    private javax.swing.JTextField jsaoliczbunki;
    private javax.swing.JButton jsaominus;
    private javax.swing.JButton jsaomnozenie;
    private javax.swing.JButton jsaonawiasy;
    private javax.swing.JButton jsaoodpowiedz;
    private javax.swing.JButton jsaopi;
    private javax.swing.JButton jsaopierwiastek;
    private javax.swing.JButton jsaoplus;
    private javax.swing.JButton jsaoprocenty;
    private javax.swing.JButton jsaorazydziesiec;
    private javax.swing.JButton jsaosilnia;
    private javax.swing.JButton jsaosinus;
    private javax.swing.JButton jsaotangens;
    private javax.swing.JButton jsaoznakrownosci;
    // End of variables declaration//GEN-END:variables
}
